# Site settings
title: LiuXin
subtitle: To be a romantic scientist
email: 15514657777@163.com
description: 梦想是成为一个浪漫科研狗 <br /> To be a romantic scientist.
baseurl:  # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author: liuxin
street_address: 225 Cedarbrae Ave UnitB
city: Waterloo
state: ON
zip_code: N2L4S6
country: Canada
phone: (1)-226-868-1016

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# Social settings
500px_url:
facebook_url:
github_url:
gitlab_url: https://gitlab.com/u/andrewbanchich
googleplus_url: https://plus.google.com/u/0/+AndrewBanchich
instagram_url: https://instagram.com
linkedin_url: https://www.linkedin.com/in/andrew-banchich-a4ba1195
pinterest_url:
slack_url:
twitter_url: https://twitter.com/andrewbanchich

# Build settings
markdown: kramdown

sass:
  style: compressed
