# Site settings
title: HarryLiuXin
email: x399liu@uwaterloo.ca
description: > # this means to ignore newlines until "baseurl:"
  To be a romantic scientist.
baseurl: "/arctic-fox-theme" # the subpath of your site, e.g. /blog/
url: "http://harryliuxin.github.io" # the base hostname & protocol for your site
twitter_username: username
github_username: username

# Build settings
markdown: kramdown
markdown_ext:  markdown,mkdown,mkdn,mkd,md

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "fenced_code_blocks"]