highlighter: rouge
permalink: /:year/:month/:day/:title.html
name: "Harry liuXin"
markdown: kramdown

author: "liuxin"
atom-baseurl: "http://liuxin.in"
disqus: "gopherwood"

navigations:
  - title: Archive
    class: fa fa-list-ul
    href: /archive.html
  - title: Tags
    class: fa fa-tags
    href: /tags.html
  - title: About
    class: fa fa-user
    href: /about.html
  - title: Gallery
    class: fa fa-film
    href: http://www.miaopai.com/u/wxsso_p4mslofx14
  - title: Subscribe
    class: fa fa-rss
    href: /atom.xml

