markdown: kramdown
highlighter: rouge

permalink: blog/:year/:month/:day/:title.html
paginate: 7
paginate_path: page/:num
encoding: "utf-8"
future: true
lsi: false
safe: true
gems: [jekyll-paginate]

blog:
    name: liuxin # 博客名称
    description: To be a romantic scientist # 博客描述
    title: 刘鑫的博客 # 网页标题
    url: liuxin.in # 博客地址
    duoshuo: 6264845519328117506 # 多说ID
    tongji: x399liu # 百度统计ID
    qiniu: # 七牛云地址
author:
    name: 刘鑫 # 作者名称
    email: 15514657777@163.com # 邮箱地址
    weibo: http://weibo.com/u/2377304267 # 微博地址
    github: https://github.com/harryliuxin # GitHub地址
    logo: /res/img/psb.jpg # logo地址
    douban:
        name: http://www.douban.com/people/98112169/    # 豆瓣地址名称
        key:             # 豆瓣API Key
